language: python

python:
  - "3.5.1"

services:
  - postgresql

cache: pip

install:
  - make install-dev
  - pip install coveralls

before_script:
  - psql -c "CREATE ROLE timed CREATEDB LOGIN PASSWORD 'timed';" -U postgres

script: make test

after_success: coveralls
