language: python

python:
  - "3.5.1"

services:
  - postgresql

cache: pip

install:
  - make install

before_script:
  - psql -c "CREATE ROLE timed LOGIN PASSWORD 'timed';" -U postgres
  - psql -c "CREATE DATABASE test_timed;" -U postgres

script: make test
