language: python

python:
  - "3.5.2"

services:
  - postgresql

cache:
  - pip
  - directories:
    - .hypothesis

install:
  - make install-dev
  - pip install coveralls

before_script:
  - psql -c "CREATE ROLE timed CREATEDB LOGIN PASSWORD 'timed';" -U postgres

script: make test

after_success: coveralls
