language: python

python:
  - "3.5.2"

services:
  - postgresql

cache: pip

install:
  - make install-dev
  - pip install coveralls
  - pip install travis-sphinx

before_script:
  - cp timed/config.sample.ini timed/config.ini
  - psql -c "CREATE ROLE timed CREATEDB LOGIN PASSWORD 'timed';" -U postgres

script:
  - make test
  - travis-sphinx build

after_success:
  - coveralls
  - travis-sphinx deploy
