version: '2'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=timed
      - POSTGRES_PASSWORD=timed
  ucs:
    build: ./docker/ucs
    hostname: timed-ucs
    volumes:
      - ./docker/ucs/timed-ucs.profile:/var/cache/univention-system-setup/profile
      - ./docker/ucs/scripts:/usr/ucs/scripts
    ports:
      - '389:389'
      - '8080:80'
    environment:
      - rootpwd=univention
