version: '2'
services:
  db:
    image: postgres:9.4
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=timed
      - POSTGRES_PASSWORD=timed
  ucs:
    image: univention/ucs-master-amd64:4.2-1
    hostname: timed-ucs
    expose:
      - 80
      - 389
    volumes:
      - ./docker/ucs/timed-ucs.profile:/var/cache/univention-system-setup/profile
      - ./docker/ucs/scripts:/usr/ucs/scripts
  backend:
    build: .
    ports:
      - '8000:80'
    volumes:
      - .:/app
    depends_on:
      - db
      - ucs
    environment:
      - DATABASE_URL=psql://timed:timed@db:5432/timed
      - ENV=docker
      - STATIC_ROOT=/var/www/static
