name: Test

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-${{ hashFiles('poetry.lock')}}
          restore-keys: |
            peotry-
      - name: Build the project
        run: |
          echo "ENV=dev" > .env
          docker-compose up -d --build backend
      - name: Lint the code
        run: |
          docker-compose exec -T backend poetry run black --check .
          docker-compose exec -T backend poetry run flake8
          docker-compose exec -T backend poetry run python manage.py makemigrations --check --dry-run --no-input
      - name: Run pytest
        run: docker-compose exec -T backend poetry run pytest --no-cov-on-fail --cov --create-db -vv
